<?php
$page['dir'] = '\\housekeeping';
$page['housekeeping'] = true;
$page['rank'] = 5;
require_once('../includes/core.php');
require_once('./includes/hksession.php');
$database=new Database(); $e=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8'); $notice=''; $action=$_GET['do']??'list';
if($_SERVER['REQUEST_METHOD']==='POST'){$id=(int)($_POST['id']??0);if($action==='delete'){$database->execute('DELETE FROM phpretro_collectibles WHERE id=?',[$id]);$notice='Collectible removed.';}else{$v=[trim((string)($_POST['name']??'')),trim((string)($_POST['description']??'')),trim((string)($_POST['image']??'')),(int)($_POST['time']??0)];if(in_array('',array_slice($v,0,3),true)||$v[3]<=0){$notice='Name, description, image, and month timestamp are required.';}elseif($id>0){$database->execute('UPDATE phpretro_collectibles SET name=?,description=?,image=?,time=? WHERE id=?',[...$v,$id]);$notice='Collectible updated.';}else{$database->execute('INSERT INTO phpretro_collectibles (name,description,image,time) VALUES (?,?,?,?)',$v);$notice='Collectible created.';}}$action='list';}
$item=['id'=>0,'name'=>'','description'=>'','image'=>'','time'=>strtotime(date('Y-m-01 00:00:00'))];if($action==='edit'){$loaded=$database->fetchRow('SELECT id,name,description,image,time FROM phpretro_collectibles WHERE id=?',[(int)($_GET['id']??0)]);if($loaded!==false){$item=$loaded;}}
ob_start();if($action==='create'||$action==='edit'){?><form method="post"><input type="hidden" name="id" value="<?php echo(int)$item['id'];?>"><label>Name</label><br><input name="name" value="<?php echo $e($item['name']);?>"><br><label>Description</label><br><textarea name="description"><?php echo $e($item['description']);?></textarea><br><label>Image URL</label><br><input name="image" value="<?php echo $e($item['image']);?>"><br><label>Month timestamp</label><br><input type="number" name="time" value="<?php echo(int)$item['time'];?>"><br><button>Save</button></form><?php }else{$rows=$database->fetchAll('SELECT id,name,image,time FROM phpretro_collectibles ORDER BY time DESC');?><p><a href="<?php echo PATH;?>/housekeeping/collectables?do=create">New collectible</a></p><table><tr><th>Name</th><th>Month</th><th>Image</th><th>Actions</th></tr><?php foreach($rows as $row){?><tr><td><?php echo $e($row['name']);?></td><td><?php echo date('F Y',(int)$row['time']);?></td><td><?php echo $e($row['image']);?></td><td><a href="<?php echo PATH;?>/housekeeping/collectables?do=edit&id=<?php echo(int)$row['id'];?>">Edit</a><form style="display:inline" method="post" action="<?php echo PATH;?>/housekeeping/collectables?do=delete"><input type="hidden" name="id" value="<?php echo(int)$row['id'];?>"><button>Delete</button></form></td></tr><?php }}?></table><?php $content=ob_get_clean();
$page['name'] = 'Collectibles'; $page['category'] = 'tools'; require_once('./templates/housekeeping_header.php');
?>
<div class="page_title"><span class="page_name">Collectibles</span></div><div class="page_main"><div class="center"><?php if ($notice !== '') { ?><div class="clean-ok"><?php echo $e($notice); ?></div><?php } ?><?php echo $content; ?></div></div><?php require_once('./templates/housekeeping_footer.php'); ?>
