<?php
declare(strict_types=1);
session_start();
require_once __DIR__ . '/../includes/Database.php';
function statements(string $sql): array { $sql = preg_replace('/^\s*--.*$/m', '', $sql) ?? ''; return array_values(array_filter(array_map('trim', explode(';', $sql)))); }
$step = max(1, min(6, (int) ($_SESSION['polaris_step'] ?? 1))); $error = null; $messages = [];
if ($_SERVER['REQUEST_METHOD'] === 'POST') { $action = $_POST['action'] ?? 'next'; if ($action === 'back') { $step = max(1, $step - 1); } else { try { if ($step === 2 || $step === 6) { $db = new Database(); if ($db->fetchColumn('SELECT 1 FROM users LIMIT 1') === false) throw new RuntimeException('Polaris users table was not found. Import CleanDB.sql first.'); if ($step === 6) { $db->execute('CREATE TABLE IF NOT EXISTS phpretro_schema_migrations (filename VARCHAR(255) NOT NULL PRIMARY KEY, applied_at INT NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4'); foreach (glob(__DIR__ . '/../migrations/*.sql') ?: [] as $file) { $name=basename($file); if ($db->fetchColumn('SELECT filename FROM phpretro_schema_migrations WHERE filename=?',[$name])) {$messages[]="$name already applied."; continue;} foreach (statements((string)file_get_contents($file)) as $sql) $db->execute($sql); $db->execute('INSERT INTO phpretro_schema_migrations (filename, applied_at) VALUES (?,?)',[$name,time()]); $messages[]="$name applied."; } } } if ($step < 6) $step++; } catch(Throwable $e) {$error=$e->getMessage();} } $_SESSION['polaris_step']=$step; }
$titles=[1=>'Introduction',2=>'Check',3=>'Database',4=>'Settings',5=>'Administrator',6=>'Install'];
$text=[1=>'Welcome to PHPRetro. This installer keeps the original flow while protecting Polaris.',2=>'Check the PHP 8.5 PDO connection and verified Polaris database.',3=>'Database credentials come from DB_DSN, DB_USER, and DB_PASS.',4=>'Site settings are handled by the modern configuration layer.',5=>'Use an existing Polaris staff account for administration.',6=>'Apply PHPRetro-owned migrations. Polaris tables are never changed.'];
require __DIR__ . '/installer_header.php';
?>
<div id="container"><div class="cbb process-template-box clearfix"><div id="content"><div id="header" class="clearfix"><h1><a href="#"></a></h1><ul class="stats"><li class="stats-online"><span class="stats-fig"><?php echo $step; ?>/6 <?php echo $titles[$step]; ?></span></li></ul></div><div class="process-content"><form method="post"><div id="installer-column-left"><div id="installer-section-left"><?php echo htmlspecialchars($text[$step],ENT_QUOTES,'UTF-8'); ?></div></div><div id="installer-column-right"><div id="installer-section-right"><div class="rounded rounded-blue"><h2 class="heading"><?php echo $titles[$step]; ?></h2><fieldset id="installer-fieldset"><?php if($error): ?><p class="error"><?php echo htmlspecialchars($error,ENT_QUOTES,'UTF-8'); ?></p><?php endif; foreach($messages as $m): ?><p><?php echo htmlspecialchars($m,ENT_QUOTES,'UTF-8'); ?></p><?php endforeach; if($step===2): ?><p>Validates PHP 8.5, PDO MySQL, and Polaris <code>users</code>.</p><?php endif; if($step===6): ?><p>Ready to install current PHPRetro migrations.</p><?php endif; ?></fieldset></div></div><div id="installer-buttons"><?php if($step>1): ?><button class="back" name="action" value="back">Back</button><?php endif; ?><button class="continue" name="action" value="next"><?php echo $step===6?'Install':'Continue'; ?></button></div></div></form></div><?php require __DIR__ . '/installer_footer.php'; ?>